# traefik.toml
logLevel = "INFO"
traefikLogsFile = "/opt/traefik/log/traefik.log"
accessLogsFile = "/opt/traefik/log/access.log"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":8000"
[web]
address = ":8080"

[file]
filename = "/opt/traefik/etc/rules.toml"
watch = true

